# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1.xci
# IP: The module: 'FIFO_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1.xci
# IP: The module: 'FIFO_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/github_repo/Vivado_FIFO_Test/vivado_fifo_test.srcs/sources_1/ip/FIFO_1/FIFO_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
